name: Build React and Notify API

on:
  push:
    branches:
      - main

jobs:
  build_and_notify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust Node version if needed

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the React App
      - name: Build React App
        run: npm run build

      # Step 5: Notify external API after successful build
      - name: Notify API
        env:
          API_URL: ${"https://pi.acresbyisaac.com/api/git"}      # API endpoint URL stored in repo secrets
          #API_KEY: ${{ secrets.API_KEY }}      # Optional: API key for authentication
        run: |
          curl -X POST "$API_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d '{"status": "build_complete", "branch": "main"}'
