name: Notify API

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      #Notify external API after successful build
      - name: Notify API
        env:
          API_URL: "https://pi.acresbyisaac.com/api/git"
          #API_KEY: ${{ secrets.API_KEY }}      # Optional: API key for authentication
        run: |
          curl -X POST "$API_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d '{"status": "build_complete", "branch": "main"}'
