name: Notify API via GET

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify API with GET request
        env:
          API_URL: "https://pi.acresbyisaac.com/api/git"
        run: |
          curl "$API_URL?status=build_complete&branch=main"
